// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function Enqueue(arg1:string,arg2:Record<string, any>):Promise<store.Job>;

export function ListJobs(arg1:number):Promise<Array<store.Job>>;
