// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['JobService']['Cancel'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['JobService']['ClearHistory']();
}

export function DeleteJob(arg1) {
  return window['go']['main']['JobService']['DeleteJob'](arg1);
}

export function Enqueue(arg1, arg2) {
  return window['go']['main']['JobService']['Enqueue'](arg1, arg2);
}

export function ListJobs(arg1) {
  return window['go']['main']['JobService']['ListJobs'](arg1);
}
