// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InsertBlank(arg1:string,arg2:number,arg3:string):Promise<Array<string>>;

export function Remove(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function Reorder(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function Rotate(arg1:string,arg2:Array<main.PageRotation>,arg3:string):Promise<Array<string>>;
