// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InsertBlank(arg1, arg2, arg3) {
  return window['go']['main']['PdfEditService']['InsertBlank'](arg1, arg2, arg3);
}

export function Remove(arg1, arg2, arg3) {
  return window['go']['main']['PdfEditService']['Remove'](arg1, arg2, arg3);
}

export function Reorder(arg1, arg2, arg3) {
  return window['go']['main']['PdfEditService']['Reorder'](arg1, arg2, arg3);
}

export function Rotate(arg1, arg2, arg3) {
  return window['go']['main']['PdfEditService']['Rotate'](arg1, arg2, arg3);
}
