// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<pipeline.Pipeline>>;

export function Run(arg1:pipeline.Pipeline,arg2:Array<string>):Promise<pipeline.RunResult>;

export function Save(arg1:pipeline.Pipeline):Promise<void>;
