// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['main']['PipelineService']['Delete'](arg1);
}

export function List() {
  return window['go']['main']['PipelineService']['List']();
}

export function Run(arg1, arg2) {
  return window['go']['main']['PipelineService']['Run'](arg1, arg2);
}

export function Save(arg1) {
  return window['go']['main']['PipelineService']['Save'](arg1);
}
