// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Count() {
  return window['go']['main']['SearchService']['Count']();
}

export function IndexFiles(arg1) {
  return window['go']['main']['SearchService']['IndexFiles'](arg1);
}

export function Query(arg1, arg2) {
  return window['go']['main']['SearchService']['Query'](arg1, arg2);
}
