// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Count():Promise<number>;

export function IndexFiles(arg1:Array<string>):Promise<number>;

export function Query(arg1:string,arg2:number):Promise<Array<store.SearchHit>>;
