// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<boolean>;

export function OpenPath(arg1:string):Promise<void>;

export function PickFiles():Promise<Array<string>>;

export function PickFolder():Promise<string>;

export function Ping():Promise<string>;

export function PreviewFor(arg1:string,arg2:Record<string, any>):Promise<string>;

export function PreviewSummary(arg1:string):Promise<main.PreviewSummary>;

export function PreviewText(arg1:string,arg2:number):Promise<string>;

export function RegisterPreviewFiles(arg1:Array<string>):Promise<Array<main.PreviewRef>>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SavePath(arg1:string):Promise<string>;

export function SaveRenderedPage(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<string>;

export function Version():Promise<string>;
