// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['SystemService']['CheckUpdate']();
}

export function OpenPath(arg1) {
  return window['go']['main']['SystemService']['OpenPath'](arg1);
}

export function PickFiles() {
  return window['go']['main']['SystemService']['PickFiles']();
}

export function PickFolder() {
  return window['go']['main']['SystemService']['PickFolder']();
}

export function Ping() {
  return window['go']['main']['SystemService']['Ping']();
}

export function PreviewFor(arg1, arg2) {
  return window['go']['main']['SystemService']['PreviewFor'](arg1, arg2);
}

export function PreviewSummary(arg1) {
  return window['go']['main']['SystemService']['PreviewSummary'](arg1);
}

export function PreviewText(arg1, arg2) {
  return window['go']['main']['SystemService']['PreviewText'](arg1, arg2);
}

export function RegisterPreviewFiles(arg1) {
  return window['go']['main']['SystemService']['RegisterPreviewFiles'](arg1);
}

export function RevealInFolder(arg1) {
  return window['go']['main']['SystemService']['RevealInFolder'](arg1);
}

export function SavePath(arg1) {
  return window['go']['main']['SystemService']['SavePath'](arg1);
}

export function SaveRenderedPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['SystemService']['SaveRenderedPage'](arg1, arg2, arg3, arg4, arg5);
}

export function Version() {
  return window['go']['main']['SystemService']['Version']();
}
