// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3) {
  return window['go']['main']['WatchService']['AddRule'](arg1, arg2, arg3);
}

export function ListRules() {
  return window['go']['main']['WatchService']['ListRules']();
}

export function RemoveRule(arg1) {
  return window['go']['main']['WatchService']['RemoveRule'](arg1);
}
