// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';
import {main} from '../models';

export function AddRule(arg1:string,arg2:string,arg3:pipeline.Pipeline):Promise<void>;

export function ListRules():Promise<Array<main.watchRuleOut>>;

export function RemoveRule(arg1:string):Promise<void>;
